apiVersion: ops.kubedb.com/v1alpha1
kind: MySQLOpsRequest
metadata:
  name: reconfigure-tls
  namespace: demo
spec:
  type: ReconfigureTLS  
  databaseRef:
    name:  my-group
  tls:
    requireSSL: true
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: my-issuer