apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: my-group
  namespace: demo
spec:
  version: 5.7.31
  # configSecret:
  #   name: my-config
  replicas: 3
  topology:
    mode: GroupReplication
    group:
      name: "dc002fc3-c412-4d18-b1d4-66c1fbfbbc9b"
      baseServerID: 100
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # requireSSL: true
  # tls:
  #   issuerRef:
  #     apiGroup: cert-manager.io
  #     kind: Issuer
  #     name: my-issuer
  #   certificates:
  #   - alias: server
  #     subject:
  #       organizations:
  #       - kubedb:server
  #     dnsNames:
  #     - localhost
  #     ipAddresses:
  #     - "127.0.0.1"
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io
  # podTemplate:
  #   spec:
  #     args:
  #     - --default-auth=mysql_native_password
  
